Webserver-42/webserv

Block.cpp
Block.hpp
Config.cpp
Config.hpp
ConfigLocation.cpp
ConfigLocation.hpp
ConfigParser.cpp
ConfigParser.hpp
ConfigServer.cpp
ConfigServer.hpp
ValidArguements.hpp
example
exampleInherit
tester.cpp

configuration file parser 구현입니다.
구현한 기능들은 WebServer Project에서 ConfigParser 클래스 구현 아이템 내에 체크 박스에 표시해 뒀습니다.

feat: implement parser

---

RequestLexer/Request.cpp
RequestLexer/Request.hpp
RequestLexer/RequestLexeme.hpp
RequestLexer/RequestLexer.cpp
RequestLexer/RequestLexer.hpp
RequestLexer/RequestLexerTester.cpp
RequestLexer/example

request Lexer를 일단 완성 시켰습니다.
앞의 config쪽과 비슷하게 하려했는데 다소 이상한 부분이 몇 있는것 같습니다.
startline은 한 글자씩 보면서 판단하게 되어있고,
headerline은 한 라인씩 가져와서 콜론(:) 기준으로만 나눠져 있습니다.
이곳에서 한글자씩 판단하지 않은 이유는 스페이스 문법검사 등등을 뒤의 parser에서 하기 위함입니다.
애매한 부분이 있어서 일단 이렇게 만들어 두었습니다.

lexer completed

---

Client.hpp
Config.cpp
Config.hpp
Server.cpp
Server.hpp

Server class implementation

---

Server.cpp

fix(Server::sendData): change local variable's type

---

Block.cpp
Block.hpp
Config.cpp
Config.hpp
ConfigLocation.cpp
ConfigLocation.hpp
ConfigServer.cpp
ConfigServer.hpp
Server.cpp

feat: implement Config getter/setter

---

ResponseHandler/ResponseHandler.cpp
ResponseHandler/ResponseHandler.hpp
Server.cpp
Server.hpp

feat: add functions to receive CGI response and http client request seperately

---

RequestParser/Request.cpp
RequestParser/Request.hpp
RequestParser/RequestParser.cpp
RequestParser/RequestParser.hpp
RequestParser/RequestParserTester.cpp

Request Class method 변수 타입을 enum에서 string으로 수정하였습니다.
관련하여 영향을 받는 get/set이나 enum을 쓰려고 셋팅했던 부분을 다 수정완료 하였습니다.

Request Class method 변수 타입 수정

---

RequestHandler.cpp
RequestHandler.hpp

ReqeusetHandler
-> URI를 configuration에 따라 처리함

feature request handler

---

Client.cpp
Client.hpp
Server.cpp
Server.hpp

Client(isKeepAlive): added to check if connection option is keep-alive or close
Server(handleConnection): added to handle connection between server and client when the server finishes sending response message

feat: add functions to Server and Client classes

---

Block.cpp
Block.hpp
Config.cpp
Config.hpp
ConfigLocation.cpp
ConfigLocation.hpp

fix: non-static to static funcs

fix: non-static to static funcs

---

Server.cpp

cgi 처리 방식 수정에 따라서 별도의 함수를 호출하도록 수정

fix(Server::receiveCGI): add cgiMessageParsing function call

---

RequestHandler.cpp
RequestHandler.hpp

fix: set Keep-Alive and responseAutoIndex

fix: set Keep-Alive and responseAutoIndex

---

Config.cpp
ConfigServer.cpp
ConfigServer.hpp
Server.cpp

fix: fix subtle type errors

---

Server/src/RequestHandler.cpp

fix: add html to errorFilePath

fix: add html to errorFilePath

---

Server/inc/RequestHandler.hpp
Server/src/RequestHandler.cpp

feat: isDirectoryFile and responseRedirect
isDirectoryFile 
: 파일이 디렉토리 파일인지 errno통해서 확인.
responseRedirect( statuscode, Location path)
: statuscode와 Location헤더 값인 location을 받아서 설정

feat: isDirectoryFile and responseRedirect

---

Server/inc/RequestHandler.hpp
Server/src/RequestHandler.cpp

fix: RequestHandler Error

---

Server/src/ResponseHandler.cpp

ResponseHandler에서 Content-type 누락된 부분 수정하였습니다.

ResponseHandler에서 Content-type 누락된 부분 수정하였습니다.

---

RequestParser/inc/RequestParser.hpp
RequestParser/src/RequestParser.cpp

refactor: refactor RequestParser

---

Client/inc/Response.hpp
Client/src/Response.cpp
RequestParser/inc/RequestParser.hpp
RequestParser/src/RequestParser.cpp
Server/inc/ResponseHandler.hpp
Server/inc/Server.hpp
Server/src/ResponseHandler.cpp
Server/src/Server.cpp
main.cpp

feat: handle exceptions

---

Client/inc/Response.hpp
Client/src/Response.cpp
ConfigParser/inc/ConfigLexer.hpp
ConfigParser/src/ConfigLexer.cpp
RequestParser/inc/RequestParser.hpp
RequestParser/src/RequestParser.cpp
Server/inc/ResponseHandler.hpp
Server/inc/Server.hpp
Server/src/ResponseHandler.cpp
Server/src/Server.cpp
main.cpp

refactor: static class variable 제거하고 함수 파라미터를 활용

---

Server/inc/MIMEType.hpp
Server/src/MIMEType.cpp

fix: non-static funcs in MIMIType Class

---

Files/DefaultConfig
Server/src/RequestHandler.cpp

 directoryList 부분 업데이트 하였습니다.

---

RequestParser/src/RequestLexer.cpp
RequestParser/src/RequestParser.cpp
Server/src/ResponseHandler.cpp

fix: ft_toLower 함수 수정

---

Server/src/Server.cpp

fix: receiveData string(const char *) constuctor /0 problem

fix: receiveData string(const char *) constuctor /0 problem

---

Server/src/RequestHandler.cpp
pages/upload_test/upload_delete.html
pages/upload_test/uploads/test1
pages/upload_test/uploads/test2

testpage download 추가, content-type이 해당 되는 것이 없을때 octect을 기본으로 설정함

testpage download 추가, content-type이 해당 되는 것이 없을때 octect을 기본으로 설정함 

---

ErrorPage/403.html

누락된 403페이지 업로드

---

cgi-bin/upload/upload.php

참고한 곳
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/201

업로드 성공시 status_code를 200에서 201로 변경하였습니다.
